# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61332be6ba7406daa1d29888e00bf8eb76ec007b095268fc17a40402cd0ff9dcf84765ab9a4b972ab2a1a34dae196c04e341b806e29c25cdd2641b0db2ef4a81

test:
  secret_key_base: 65b246ec46afa2768a0278a97e505dc26868d89f1e60b710c1273d8084381ddca41543ef7d6dc3edbf6cc2c1f5b54ebf29c5b673c797152e245e9447c7603c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
